---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-${worker-name}-bmc-secret
  namespace: openshift-machine-api
type: Opaque
data:
  username: cm9vdA==
  password: Y2Fsdmlu

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ${worker-name}
  namespace: openshift-machine-api
spec:
  online: true
  bmc:
    address: ipmi://${worker-bmc-ipaddr}
    credentialsName: openshift-${worker-name}-bmc-secret
  bootMACAddress: ${worker-iface-mac-sriovpr}

